name: travel_go
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  bot_toast: ^4.1.3
  flutter_easyloading: ^3.0.5
  skeletonizer: ^1.4.3
  cloud_firestore: ^5.6.2
  email_otp: ^3.0.2
  lottie: ^3.3.1
  google_sign_in: ^6.2.2
  phone_form_field: ^10.0.4
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_swipe_action_cell: ^3.1.5
  supabase: ^2.6.2
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  country_state_city_picker: ^1.2.8
  chips_choice: ^3.0.1
  searchfield: ^1.2.4
  animate_do: ^4.1.1
  google_gemini: ^0.1.2
  dio: ^5.8.0+1
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  syncfusion_flutter_charts: ^28.2.6
  awesome_alert: ^1.0.2
  youtube_player_flutter: ^9.1.1
  roundcheckbox: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/files/
    - assets/images/places/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
