// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNj4MXkZOoeBwqttrD7Ps0wWuUCEoB7l4',
    appId: '1:561387972473:android:c24fa7dd8e0f6b964cf1a8',
    messagingSenderId: '561387972473',
    projectId: 'tamohy-b7d82',
    storageBucket: 'tamohy-b7d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAEHQ7KjdtLGk6N6iKSwfidLL00vev8NE',
    appId: '1:561387972473:ios:340134778a0093c54cf1a8',
    messagingSenderId: '561387972473',
    projectId: 'tamohy-b7d82',
    storageBucket: 'tamohy-b7d82.firebasestorage.app',
    androidClientId: '561387972473-h4ea8ebd0fdp867qh987buphltcc5ol5.apps.googleusercontent.com',
    iosClientId: '561387972473-fbgj6qt5ektq1aqjrsr62kokge9bggl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelGo',
  );

}